import Navbar from "@/app/widgets/Navbar/Navbar";
import Welcome from "@/app/widgets/welcome/welcome";
import PhotoSecond from "@/app/widgets/photoSecond/photoSecond";
import AboutMe from "@/app/widgets/about/aboutMe";
import Skills from "@/app/widgets/skills/skills";
export {Navbar as Navbar}
export {Welcome as Welcome}
export {PhotoSecond as PhotoSecond}
export {AboutMe as AboutMe}
export {Skills as Skills}